apiVersion: v1
kind: Service
metadata:
  name: tictactoe-service
  labels:
    app: tictac
spec:
  type: NodePort  
  selector:
    app: tictac
  ports:
  - protocol: TCP
    port: 80      
    targetPort: 80
    nodePort: 30000
